### ISSUE TITLE
Delay on useChartPressState

### ISSUE THREAD

**Issue by fpinnola** [FormidableLabs/victory-native-xl#153]
### Prerequisites

Using Expo
expo: 49.0.13

Platform: iOS

victory-native: 40.0.2
react-native: 0.72.5
@shopify/react-native-skia: 0.1.196
react-native-reanimated: 3.3.0

### Describe the Problem

**Expected behavior:** When I press on the Chart, I should get an almost instantaneous hit on a useEffect hook from the change of isActive value.

**Actual behavior:** I need to hold down on the Chart for longer than a tap for the state change to happen.

```
export default function App() {
  const { state: pressState, isActive: pressActive } = useChartPressState({ x: 0, y: { y: 0 }});

  useEffect(() => {
    if (pressActive) {
      console.log('Tap started');
    }
  }, [pressState, pressActive]);

return (
    <View style={{ width: '100%', height: 175, marginTop: 50 }}>
        <CartesianChart 
                      padding={{ left: 10, right: 10, bottom: 10 }} 
                      domainPadding={{ top: 35, left: 15, right: 15, bottom: 20}} 
                      data={graphData} 
                      xKey="xaxis" 
                      yKeys={["y"]}
                      chartPressState={pressState}
                    >
                      {({points}) =>
                      {
                        return (
                        <>
                          <Line points={points.y} color="white" strokeWidth={3} />
                          <Scatter  
                            points={points.y}
                            shape="circle"
                            radius={10}
                            color="#b49ce8"
                          />
                        </>
                      )}}
                </CartesianChart>
    </View>

);


}
```

### Additional Information

I wonder if there is some reason behind adding this delay in preventing accidental taps on the chart, however there needs to be a way to remove the delay for fast/responsive changes on the UI.

**Comment by kajetanjasztal** [comment]
I'm having the same issue
```
victory-native: 40.0.2
@shopify/react-native-skia: 0.1.212
react-native-reanimated: 3.5.4
expo: 49.0.6
react-native: 0.72.3
```

**Comment by kajetanjasztal** [comment]
we ended up patching [this](https://github.com/FormidableLabs/victory-native-xl/blob/main/lib/src/cartesian/CartesianChart.tsx#L290) and exposing it as property of `CartesianChart`, it's not ideal but makes selecting datapoints much more responsive.

It would be useful to have more control over the gestures, so for example short press selects a datapoint on release, and longer one initiates panning.

**Comment by zibs** [comment]
This should be fixed via the latest release of `40.0.4`

**Comment by carlosriveroib** [comment]
Hello, I'm still experiencing this, sometimes to select another bar I have to press 2 or 3 times to change the bar. The opinion of my users is the charts doesn't work.

**Comment by Guuz** [comment]
Hi, this is an issue for us as well. The chart interaction feels very buggy due to this.
@zibs are you aware if this is intentional or not?

**Comment by cwqt** [comment]
@Guuz @carlosriveroib  try setting `gestureLongPressDelay={0}` on your chart, there's a 100ms delay on registering taps by default which makes it feel unresponsive
